services:
  firestore-go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./docker/service-account.json:/credentials/service-account.json:ro
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/service-account.json
    networks:
      - default
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--web.enable-remote-write-receiver" # for k6 client
      - "--enable-feature=native-histograms"
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - default
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - default
  # stackdriver-exporter:
  #   image: prometheuscommunity/stackdriver-exporter:latest
  #   command:
  #     - "--monitoring.metrics-type-prefixes=firestore.googleapis.com"
  #   ports:
  #     - "9255:9255"
  #   volumes:
  #     - ./docker/service-account.json:/credentials/service-account.json:ro
  #     # - ./docker/stackdriver-exporter.yaml:/etc/stackdriver-exporter/stackdriver-exporter.yaml:ro
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/credentials/service-account.json
  #   networks:
  #     - default
volumes:
  prometheus_data: {}

networks:
  default: