global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'firestore-go'
    static_configs:
      - targets: ['firestore-go:8080']

  - job_name: 'stackdriver-exporter'
    static_configs:
      - targets: ['stackdriver-exporter:9255']
