{
 "title": "Firestore Read Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Firestore Read 총합 (성공/실패)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(firestore_reads_total{collection=\"test-collection\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Firestore Read 초당 요청 수 (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(firestore_reads_total{collection=\"test-collection\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Firestore Read 평균 Latency[1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(firestore_read_latency_seconds_sum{collection=\"test-collection\"}[$__rate_interval]) / rate(firestore_read_latency_seconds_count{collection=\"test-collection\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firestore Read 성공/실패율(0~100%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(firestore_reads_total{collection=\"test-collection\", status=\"success\"}[$__rate_interval]) * 100) / rate(firestore_reads_total{collection=\"test-collection\"}[$__rate_interval])"
    },
    {
     "expr": "(rate(firestore_reads_total{collection=\"test-collection\", status=\"error\"}[$__rate_interval]) * 100) / rate(firestore_reads_total{collection=\"test-collection\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}